### ISSUE TITLE
Uploading other filetypes except screenshots

### ISSUE THREAD

**Issue by slobodanmargetic988** [InvisibilityInc/Invisibility#10]
would be nice if we could upload other types of files. now i cant even upload a txt file.

also feel free to contact me on slobodanmargetic988@gmail.com if you are open to collaboration. i would be more than happy to join your project and add some features like this one. this app is amazing.

**Comment by djmango** [comment]
Adding support for all Text (.txt, .csv, .log, .json, etc) and PDF files! Update will be released in the next hour. What other files would you like?

**Comment by djmango** [comment]
Shipped! can update to 2.0.14 now and try out PDFs + text files :)
