### ISSUE TITLE
Scroll to bottom , scroll to top and just scroll as the answer is being generated

### ISSUE THREAD

**Issue by slobodanmargetic988** [InvisibilityInc/Invisibility#12]
Another feature request...
Scroll to bottom , scroll to top  shortcuts needed
And just scroll as the answer is being generated  toggle button in settings or something like that.

**Comment by djmango** [comment]
Buttons are a good idea, will add. For scrolling with the answer, the way it works currently is that if you scroll to the bottom, it will "lock" and if you scroll up it will "unlock". This interaction can certainly be improved, I will work to do so.
