### ISSUE TITLE
Not able to interact with the UI - Mac OS Sequoia 

### ISSUE THREAD

**Issue by nikhilesh1234** [InvisibilityInc/Invisibility#15]
![CleanShot 2024-07-30 at 00 29 33](https://github.com/user-attachments/assets/cf99f306-cafa-4d1a-8ce3-b5cf27f9ad75)

The UI is not intractable using a mouse, but the keyboard works fine.

![CleanShot 2024-07-30 at 00 31 57](https://github.com/user-attachments/assets/af4ee2a6-66c7-47d5-90bf-6cfbf6add56c)

**Comment by djmango** [comment]
Fixed in latest release! 2.3.3
