### ISSUE TITLE
Daily limit reached never goes away

### ISSUE THREAD

**Issue by Facecloth4523** [InvisibilityInc/Invisibility#16]
Updated to v2.3.6 and the "daily limit reached" message has been there since. I have not been able to use it a single time since the updated. Have switched to different LLMs with no success!

**Comment by Facecloth4523** [comment]
Have not been able to use the app for more than two months. What's going on?

**Comment by djmango** [comment]
Hey! We're phasing out our free tier and upgrading our premium tiers, as we add more top-of-the-line models like the new o1 preview and upcoming 3.5 Opus. Let me know if I can be of any more help!
