### ISSUE TITLE
Could not connect to server - fully onboarded and paid...

### ISSUE THREAD

**Issue by ericjuta** [InvisibilityInc/Invisibility#5]
![Screenshot 2024-03-14 at 13 04 05](https://github.com/InvisibilityInc/Invisibility/assets/3833339/0de2e227-0651-49e7-86a5-4e94205cdd32)

**Comment by djmango** [comment]
Did this issue reoccur? We've pushed a few patches now, should resolve your error

**Comment by djmango** [comment]
Close for inactivity + no repeat occurances
