### ISSUE TITLE
⚙️ Settings Bug: Getting it to appear at the top

### ISSUE THREAD

**Issue by ricburton** [InvisibilityInc/Invisibility#9]
Whether in app or from menubar, the settings window does not come to the top when I select it.

**Comment by djmango** [comment]
Big one for me as well. Bumping for next release

**Comment by djmango** [comment]
Fix shipped with 2.0.14, can update now :)

<img width="377" alt="image" src="https://github.com/InvisibilityInc/Invisibility/assets/28496988/38acc35d-f04a-4f08-95d0-10846a20a70f">
